### ISSUE TITLE
Multiplayer connectivity issues re: Data Serializers

### ISSUE THREAD

**Issue by noobanidus** [RedstoneTim/aswampscurse#2]
After an extensive conversation with Gigaherz and modifying my own mod (which used a custom data serializer):

![](https://i.imgur.com/d8wq3Zb.png)

![](https://i.imgur.com/olff7Hq.png)

Registering it statically in the static init of the entity class can cause a race condition where the serializer isn't properly registered, resulting in people suffering from difficulty connecting to servers, especially when they're connecting to near a swampy area.

I'm really looking forward to playing around with this mod, unfortunately I've had to remove it from the server for now.

**Comment by RedstoneTim** [comment]
Thanks again for your help!
I've handled the situation by replacing the long with a string since looking back at it, it wasn't really worth adding a whole new data serializer for that and string is just the easiest to implement.
(I know that a new data serializer would've been the cleanest way to do that, but I really don't want to get more bugs into this just for one small class.)
