### ISSUE TITLE
Conflict with Spidercraft

### ISSUE THREAD

**Issue by AechtRob** [RedstoneTim/aswampscurse#3]
I seem to have a conflict between this mod and SpiderCraft.... do you have any idea which mod is at fault or whether an update is needed? Log is attached:

[log.txt](https://github.com/RedstoneTim/aswampscurse/files/4332749/log.txt)

**Comment by RedstoneTim** [comment]
I'm sorry that we haven't fixed this bug (a new update would've been needed from our side) and never answered.
Now we've decided to stop developing this project since we don't really care about the mod anymore. The code was flawed from the beginning, had way too many issues and the whole project was just rushed.
A Swamp's Curse is now licensed under MIT so other people could continue it if they wanted to, but we're not going to (at least not in the near future).
